export enum Style {
    Baroque = 1,
    Bauhaus = 2,
    RussianRevival = 3,
    QueenAnne = 4,
    AncientEgyptian = 5,
    Postmodern = 6,
    Colonial = 7,
    ArtDeco = 8,
    TudorRevival = 9,
    Romanesque = 10,
    International = 11,
    Deconstructivism = 12,
    Palladian = 13,
    Gothic = 14,
    BeauxArts = 15,
    Byzantine = 16,
    Georgian = 17,
    Edwardian = 18,
    Novelty = 19,
    Achaemenid = 20,
    AmericanFoursquare = 21,
    ArtNouveau = 22,
    ChicagoSchool = 23,
    AmericanCraftsman = 24,
    GreekRevival = 25
}

export const StyleByStringName = {
    ['baroque']: Style.Baroque,
    ['russianRevival']: Style.RussianRevival,
    ['queenAnne']: Style.QueenAnne,
    ['ancientEgyptian']: Style.AncientEgyptian,
    ['postmodern']: Style.Postmodern,
    ['colonial']: Style.Colonial,
    ['artDeco']: Style.ArtDeco,
    ['tudorRevival']: Style.TudorRevival,
    ['romanesque']: Style.Romanesque,
    ['international']: Style.International,
    ['deconstructivism']: Style.Deconstructivism,
    ['palladian']: Style.Palladian,
    ['gothic']: Style.Gothic,
    ['beauxArts']: Style.BeauxArts,
    ['byzantine']: Style.Byzantine,
    ['georgian']: Style.Georgian,
    ['edwardian']: Style.Edwardian,
    ['novelty']: Style.Novelty,
    ['achaemenid']: Style.Achaemenid,
    ['americanFoursquare']: Style.AmericanFoursquare,
    ['artNouveau']: Style.ArtNouveau,
    ['chicagoSchool']: Style.ChicagoSchool,
    ['americanCraftsman']: Style.AmericanCraftsman,
    ['greekRevival']: Style.GreekRevival,
    ['bauhaus']: Style.Bauhaus
};

export const StyleNameString = {
    [Style.Baroque]: 'Baroque',
    [Style.Bauhaus]: 'Bauhaus',
    [Style.RussianRevival]: 'Russian Revival',
    [Style.QueenAnne]: 'Queen Anne',
    [Style.AncientEgyptian]: 'Ancient Egyptian',
    [Style.Postmodern]: 'Postmodern',
    [Style.Colonial]: 'Colonial',
    [Style.ArtDeco]: 'ArtDeco',
    [Style.TudorRevival]: 'Tudor Revival',
    [Style.Romanesque]: 'Romanesque',
    [Style.International]: 'International',
    [Style.Deconstructivism]: 'Deconstructivism',
    [Style.Palladian]: 'Palladian',
    [Style.Gothic]: 'Gothic',
    [Style.BeauxArts]: 'Beaux Arts',
    [Style.Byzantine]: 'Byzantine',
    [Style.Georgian]: 'Georgian',
    [Style.Edwardian]: 'Edwardian',
    [Style.Novelty]: 'Novelty',
    [Style.Achaemenid]: 'Achaemenid',
    [Style.AmericanFoursquare]: 'American Foursquare',
    [Style.ArtNouveau]: 'Art Nouveau',
    [Style.ChicagoSchool]: 'Chicago School',
    [Style.AmericanCraftsman]: 'American Craftsman',
    [Style.GreekRevival]: 'Greek Revival'
};
