export enum Style {
    Baroque = 1,
    Bauhaus = 2,
    RussianRevival,
    QueenAnne,
    AncientEgyptian,
    Postmodern,
    Colonial,
    ArtDeco,
    TudorRevival,
    Romanesque,
    International,
    Deconstructivism,
    Palladian,
    Gothic,
    BeauxArts,
    Byzantine,
    Georgian,
    Edwardian,
    Novelty,
    Achaemenid,
    AmericanFoursquare,
    ArtNouveau,
    ChicagoSchool,
    AmericanCraftsman,
    GreekRevival
}

export const StyleByStringName = {
    ['baroque']: Style.Baroque,
    ['russianRevival']: Style.RussianRevival,
    ['queenAnne']: Style.QueenAnne,
    ['ancientEgyptian']: Style.AncientEgyptian,
    ['postmodern']: Style.Postmodern,
    ['colonial']: Style.Colonial,
    ['artDeco']: Style.ArtDeco,
    ['tudorRevival']: Style.TudorRevival,
    ['romanesque']: Style.Romanesque,
    ['international']: Style.International,
    ['deconstructivism']: Style.Deconstructivism,
    ['palladian']: Style.Palladian,
    ['gothic']: Style.Gothic,
    ['beauxArts']: Style.BeauxArts,
    ['byzantine']: Style.Byzantine,
    ['georgian']: Style.Georgian,
    ['edwardian']: Style.Edwardian,
    ['novelty']: Style.Novelty,
    ['achaemenid']: Style.Achaemenid,
    ['americanFoursquare']: Style.AmericanFoursquare,
    ['artNouveau']: Style.ArtNouveau,
    ['chicagoSchool']: Style.ChicagoSchool,
    ['americanCraftsman']: Style.AmericanCraftsman,
    ['greekReviva']: Style.GreekRevival
};
